spring:
##redis配置
  profiles: prod
  redis:
    database: 0
    host: 2df27a68346746ba.m.cnhza.kvstore.aliyuncs.com
    port: 6379
    password: 2df27a68346746ba:h2omeRedis
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  #hardware-druid-datasource
  hardware-druid-datasource:
    url: jdbc:mysql://rds03jhkvv73853nd232.mysql.rds.aliyuncs.com:3306/narcissus?useSSL=false&serverTimezone=GMT%2b8
    username: xiaoshuidi
    password: ACA6VdyocBuTNduF
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}

  #volga-druid-datasource
  volga-druid-datasource:
    url: jdbc:mysql://rds03jhkvv73853nd232.mysql.rds.aliyuncs.com:3306/volga-pro?useSSL=false&serverTimezone=GMT%2b8
    username: xiaoshuidi
    password: ACA6VdyocBuTNduF
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}

  #caspain-druid-datasource
  caspain-druid-datasource:
    url: jdbc:mysql://rds03jhkvv73853nd232.mysql.rds.aliyuncs.com:3306/caspain_pro?useSSL=false&serverTimezone=GMT%2b8
    username: xiaoshuidi
    password: ACA6VdyocBuTNduF
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}

  #lijiang-druid-datasource
  lijiang-druid-datasource:
    url: jdbc:mysql://rds03jhkvv73853nd232.mysql.rds.aliyuncs.com:3306/lijiang?useSSL=false&serverTimezone=GMT%2b8
    username: xiaoshuidi
    password: ACA6VdyocBuTNduF
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${publicKey}


server:
  port: 9181
  max-http-header-size: 10000000

#短信平台地址
sms:
  baseUrl: http://xs1:5312

bigCustomersInfo: 22886

#平安配置文件
pingan:
  sdkPrefix: prod
  wxPay:
    shuidiUrl: http://finance.shuidiguanjia.com/finance/
    baseUrl: https://mixpayuat4.orangebank.com.cn/mct1/
    open_id: ee757f1f219759974563dc80acc43b77
    open_key: 333d153b8b16a5e07e297891e70552e8
    #文件传输用户短号
    uid: M39479